feat: to review
bartosz-io/dev-academy-2.0 pull request #36
Opened 2022-10-02 17:30 UTC by cr0wg4n

csurf post to review

2022-11-13 12:51 UTC, bartosz-io requested changes

2022-11-16 02:25 UTC, cr0wg4n commented on source/_posts/csurf-vulnerability.md
> +As a developer in a back-end role, sometimes we delegate the weight of complex mechanisms implementation to popular libraries in the ecosystem. Maybe it resolves the problem and saves a lot of time,
Done :D

2022-11-16 02:25 UTC, cr0wg4n commented on source/_posts/csurf-vulnerability.md
> +{% img "dsc.png" "csurf package overview" "lazy" %}
yeah, is my image :D

2022-11-16 02:26 UTC, cr0wg4n commented on source/_posts/csurf-vulnerability.md
> +---
Done :D

2022-11-17 14:19 UTC, cr0wg4n commented on source/_posts/csurf-vulnerability.md
> +- `cookie-signature`, could be bypassed changing the library code (this issue was a game changer because we believed signing the cookies solved part of the problem).
- `cookie-signature` dependency could be bypassed changing the library code (this issue was a game changer because we believed signing the cookies solved part of the problem).

I explained the main problem below

2022-11-17 15:17 UTC, bartosz-io commented on source/_posts/csurf-vulnerability.md
> +- `cookie-signature`, could be bypassed changing the library code (this issue was a game changer because we believed signing the cookies solved part of the problem).
But how does it relate to a deployed vulnerable site that is under risk (you cannot change node_module there)?

2022-11-17 15:26 UTC, bartosz-io commented on package.json
> +    "build": "npm rebuild node-sass && hexo generate",
Please roll back this change. We need to add `node-sass@4.14` to `package.json` to make this a part of the installation.

2022-11-18 18:48 UTC, cr0wg4n commented on source/_posts/csurf-vulnerability.md
> +- `cookie-signature`, could be bypassed changing the library code (this issue was a game changer because we believed signing the cookies solved part of the problem).
This article contains two cases. The first one is Adrian's write-up, and the second explains how the attack could be possible even if the cookies are signed, but that case needs to steal the victim's csrf token, toss that, and create its csrf token with the _csrf steeled cookie. In that way, the attacker needs to modify the cookie-signature package at its side to bypass the cookie verification. 

I use this video https://www.youtube.com/watch?v=lsaTgqJGzRc and this POC (https://github.com/veryriskyrisk/csurf-attack-poc) to test the vulnerability, even I change the code to reproduce the Adrian's write-up

2022-11-20 12:59 UTC, bartosz-io commented on source/_posts/csurf-vulnerability.md
> +- `cookie-signature`, could be bypassed changing the library code (this issue was a game changer because we believed signing the cookies solved part of the problem).
Oh - you mean to manipulate to package locally to sign the cookie on your machine that will be accepted on the victim's machine? Maybe as **a last touch** to the article express this approach explicitly? 🦾

2022-11-26 18:37 UTC, bartosz-io approved these changes

2022-11-26 18:37 UTC, merged