Angular cli HTTPS added
bartosz-io/dev-academy-2.0 pull request #39
Opened 2022-10-10 10:11 UTC by AMSANJEEV28

2022-10-10 10:57 UTC, bartosz-io requested changes

2022-10-10 10:57 UTC, bartosz-io commented on source/_posts/running-angular-cli-over-https.md
> +author: A M Sanjeev
please change `author` to `contributor`

2022-10-10 11:04 UTC, AMSANJEEV28 commented on source/_posts/running-angular-cli-over-https.md
> +author: A M Sanjeev
Done

2022-11-13 12:52 UTC, bartosz-io commented
Are you going to update the article @AMSANJEEV28 ?

2022-12-11 18:07 UTC, bartosz-io approved these changes

2022-12-11 18:07 UTC, merged