Csrf edit
bartosz-io/dev-academy-2.0 pull request #49
Opened 2022-12-23 21:50 UTC by geogramdotcom

Pull request for CSRF update

2022-12-26 20:35 UTC, bartosz-io commented
How about adding a quote block with a">" sign at **the very beginning** of the article:

> The article was updated on 20th December 2022 to reflect the current state of XYZ and ABC.

Or something similar?

2022-12-26 20:39 UTC, bartosz-io commented on source/_posts/angular-csrf-protection-implementation.md
> +// Use body-parser
What is the value of these comments? They do not seem to add anything...

2022-12-26 20:39 UTC, bartosz-io commented on source/_posts/angular-csrf-protection-implementation.md
> +Instead of using the CSURF npm package, you should use the following implimentation on the server.
implimentation -> typo

2022-12-26 20:39 UTC, bartosz-io commented on source/_posts/angular-csrf-protection-implementation.md
> +To block the potential liability of Javascript accessing the cookie and user data there is a flag that can be implemented to prevent this type of attack. The “HttpOnly” flag is used to block Javascri
HttpOnly => `HttpOnly` (with ticks \`\`)

2022-12-26 20:39 UTC, bartosz-io commented on source/_posts/angular-csrf-protection-implementation.md
> +When the client receives the CSRF token from the server, there are two options to use for the server to validate that the request is legitimate.
A new line here?

2022-12-26 20:40 UTC, bartosz-io commented
How about adding some simple visuals (diagram or graph) explaining CSRF ?

You could take the ones from the Web Security Academy lesson about CSRF :)

- [ ] Consider adding a visual

2023-01-11 15:45 UTC, bartosz-io commented
@geogramdotcom any updated on this?

2023-02-24 19:50 UTC, devcodedcom requested changes

2023-02-24 19:50 UTC, devcodedcom commented on source/_posts/angular-csrf-protection-implementation.md
> +1) Every XHR request sent out has to include a custom HTTP header with a specific name and value; this can also be coupled with the user's session id token called "double submit cookie method". Be wa
TYPO in `implimentation `

2023-02-26 10:29 UTC, devcodedcom requested changes

2023-02-26 10:29 UTC, devcodedcom commented on source/_posts/angular-csrf-protection-implementation.md
> +**UPDATE:** This article was updated Feb. 25, 2023 to include information on CSURF Package Vulnerability. For those who have implimented a CSRF prevention method using CSURF, a popular Node.js CSRF p
Also TYPO in implimented ->implemented

2023-02-27 15:59 UTC, geogramdotcom commented on source/_posts/angular-csrf-protection-implementation.md
> +**UPDATE:** This article was updated Feb. 25, 2023 to include information on CSURF Package Vulnerability. For those who have implimented a CSRF prevention method using CSURF, a popular Node.js CSRF p
Removed the Date, but left the update note.

2023-02-27 16:07 UTC, geogramdotcom commented on source/_posts/angular-csrf-protection-implementation.md
> +    secret: CSRF_SECRET,
`secret` is correct per csrf-csrf docs https://github.com/Psifi-Solutions/csrf-csrf/blob/9be23b3bd28a69caec99c5951a5a0ac7968168cc/README.md?plain=1#L195

2023-03-03 16:04 UTC, devcodedcom approved these changes

2023-03-03 16:09 UTC, bartosz-io approved these changes

2023-03-03 16:09 UTC, merged

2023-03-03 18:39 UTC, geogramdotcom commented
👏