angular-input-validation
bartosz-io/dev-academy-2.0 pull request #54
Opened 2023-01-20 22:02 UTC by AMSANJEEV28

- by AMSanjeev

2023-01-21 10:57 UTC, bartosz-io requested changes

2023-01-21 10:57 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +description: Learn how to  create and validate Angular Forms.
duplicated spaces - please fix

2023-01-21 10:57 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +Angular has a few built-in validators to verify common use cases. If we want the validations to use built-in validators, we would need to apply validation attributes to every form field. These valida
Please remove the `\` and use ticks to highlight the syntax.

2023-01-21 10:57 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +          ]
All the code snippets need to be fixed to use triple ticks ```

2023-01-21 10:57 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +    ![](https://images.surferseo.art/e9327bfe-9da1-48d1-b691-05809321d7c3.png)
All the images need to be uploaded.

2023-01-21 17:56 UTC, bartosz-io requested changes

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +## Template driven forms
template-driven

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +In Template Driven Forms, we focus on the actions and validations by using directives and attributes in our template and letting it work behind the scenes. Everything happens in Template. The compone
template-driven

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +    ```
The snippets should not have additional spaces/tabs. Please remove all.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +    {% img "appcomponent.png" "Add codes to appcomponent.html" "lazy" %}
The same here: additional spaces/tabs. Please remove all.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +
Too many new lines...

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +*   We will do this by including the following code in our `form` tag.
Too many spaces.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +1.  For this, we are going to add `#variable ="ngModel"` to our input fields. Here I've named our `variable` as `name`.
Too many spaces.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +    ```
The formatting of that snippet is totally broken. Please fix it.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +[key: string]: any;
Missing tab.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +(control: AbstractControl): ValidationErrors | null
Missing tab.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +<form>
Formatting.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +```
Formatting.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +<form>
Formatting.

2023-01-21 17:56 UTC, bartosz-io commented on source/_posts/angular-input-validation.md
> +```
Formatting.

2023-01-21 19:11 UTC, AMSANJEEV28 commented
Done

2023-01-22 13:21 UTC, bartosz-io approved these changes

2023-01-22 13:21 UTC, merged